name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # LIBGPG_ERROR_PREFIX: "gpg-error"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: sudo apt-get update && sudo apt-get install -y libgmime-3.0-dev libglib2.0-dev libglib2.0-dev-bin gnupg-utils gnupg2 gpgconf gpgrt-tools libgpgme-dev librust-gpgme-dev librust-gpgme-sys-dev libgpg-error-dev librust-libgpg-error-sys-dev libgpg-error0 php-gnupg
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
