name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: fedora-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: sudo dnf check-update && sudo dnf install gnupg2 libgpg-error libgpg-error-devel
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
