name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  # LIBGPG_ERROR_PREFIX: "gpg-error"
  GPGME_PREFIX: "gpgme-tool"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup
      run: sudo apt-get -y update && sudo apt-get install -y libgpgme-dev && sudo apt-get install -y libgpg-error libgpg-error-dev
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
